### PR TITLE
Fix long option followed by single dash

### LINKED ISSUE #15: `-` can not be string value
The regex `/^-/` matches `-`, making argument valued by `-` character only not available.
`-` is commonly used as the reference of stdin.

https://github.com/minimistjs/minimist/blob/5784b17f4905939c14037b2e80e36c62b7d0e68b/index.js#L167

### PR DESCRIPTION
**Pull request by shadowspawn**
A single dash is used with some utilities to represent stdin/stdout, as an argument or as an option value. Minimist was allowing a single dash as a space-separated value for a short option but not for a long option.

Fixes #15

This PR uses the same pattern for checking a potential long-option value as already being used for checking the short-option value. In particular, this means a single dash is now accepted as an option value when used like:

```
util --foo -
```

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -164,7 +164,7 @@ module.exports = function (args, opts) {
 			next = args[i + 1];
 			if (
 				next !== undefined
-				&& !(/^-/).test(next)
+				&& !(/^(-|--)[^-]/).test(next)
```
Comment (ljharb) [inline index.js:167]: i notice here you're careful to disallow three or more dashes - can we add a test for that?

**Review by ljharb — COMMENTED** [review]
This is great!

File: index.js (hunk 1 above)
Comment (shadowspawn) [reply index.js:167]: Ok, I'll check how much I believe triple dash is a supported behaviour, and either add tests or explain why I think it is suspect. 😄 

(The test came from existing code.)

Comment (shadowspawn) [reply index.js:167]: Added test, as much to show short and long option now consistent as for the outcome.

File: test/dash.js [hunk 2]
```diff
@@ -4,8 +4,11 @@ var parse = require('../');
 var test = require('tape');
 
 test('-', function (t) {
-	t.plan(5);
+	t.plan(8);
 	t.deepEqual(parse(['-n', '-']), { n: '-', _: [] });
+	t.deepEqual(parse(['--nnn', '-']), { nnn: '-', _: [] });
+	t.deepEqual(parse(['-n', '---']), { n: '---', _: [] });
+	t.deepEqual(parse(['--nnn', '---']), { nnn: '---', _: [] });
```
Comment (ljharb) [inline test/dash.js]: i hadn't considered this as the value, but these are good - what about `---nnn=abc`?

Comment (shadowspawn) [reply test/dash.js]: `---nnn=abc` is not affected by this PR, which only affects processing of a long option with a space separated value which starts with a dash.

For interest, the behaviour before and after is:
```console
% node plain.js ---nnn=abc
{ _: [], '-nnn': 'abc' }
```

File: test/dash.js [hunk 3]
```diff
@@ -4,8 +4,11 @@ var parse = require('../');
 var test = require('tape');
 
 test('-', function (t) {
```
Comment (shadowspawn) [inline test/dash.js:6]: Just noticed the new `---` value tests don't belong in the existing test group, which is concisely titled `-`. I'll move them.

File: test/dash.js (hunk 2 above)
Comment (ljharb) [reply test/dash.js]: ok, then `---nnn abc`?

Comment (ljharb) [reply test/dash.js]: ohhh you're saying the regex in question only applies to the value, not the key. gotcha

File: test/dash.js (hunk 3 above)
Comment (shadowspawn) [reply test/dash.js:6]: Refactored so logically grouped.

**Review by ljharb — APPROVED** [review]

**Review by Hugo7825 — APPROVED** [review]
